### ISSUE TITLE
PHP MySQL Date Convert

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#1]
| Q                          | A
| ----------------------- | ---
| Language             | php
| Description           | Convert german date field into "MySQL Date"
| Search Keywords | php, mysql, date, time, convert

```php
/**
 * Converts Date Field from dd.mm.yyyy to yyyy-mm-dd or yyyy-mm-dd hh:ii:ss
 *
 * @param  string  $date
 * @param  boolean $with_time
 * @return string  mysql-fitting date
 */
function generateMySQLDate($date, $with_time) {

  if($with_time) :

    $buffer = explode(' ', $date);
    $date   = explode('.', $buffer[0]);
    $time   = explode(':', $buffer[1]);
    return $buffer[2].'-'.$buffer[1].'-'.$buffer[0].' '.$time[0].':'.$time[1].':'.$time[2];
  else :

    $buffer = explode('.', $date);
    return $buffer[2].'-'.$buffer[1].'-'.$buffer[0];
  endif;
}
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/2

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: http://www.codequote.de/php/php-mysql-date-convert
