### ISSUE TITLE
Now, God only knows

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#11]
| Q               | A
| --------------- | ---
| Language        | comment
| Description     | When I wrote this, only God and I understood what I was doing. Now, God only knows
| Search Keywords | understood, god, only

```php
// When I wrote this, only God and I understood what I was doing
// Now, God only knows
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/12

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/now-god-only-knows
