### ISSUE TITLE
Real programmers don’t comment their code

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#13]
| Q               | A
| --------------- | ---
| Language        | none
| Description     | Real programmers don’t comment their code
| Search Keywords | programmers, developers, comment, hard, understand

```php
// Real programmers don’t comment their code – it was hard to write, it should be hard to understand.
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/14

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/real-programmers-dont-comment-their-code
