### ISSUE TITLE
Happy debugging, suckers!

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#15]
| Q               | A
| --------------- | ---
| Language        | comment
| Description     | happy debugging, suckers!
| Search Keywords | debug, debugging, define, true, false

```php
# define TRUE FALSE
// Happy debugging, suckers!
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/16

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/happy-debugging-suckers
