### ISSUE TITLE
I dedicate all this code, all my work, to my wife, Darlene!

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#17]
| Q               | A
| --------------- | ---
| Language        | comment
| Description     | I dedicate all this code, all my work, to my wife, Darlene
| Search Keywords | work, dedicate, support, public

```php
// I dedicate all this code, all my work, to my wife, Darlene, who will 
// have to support me and our three children and the dog once it gets 
// released into the public.
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/18

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/i-dedicate-all-this-code-all-my-work-to-my-wife-darlene
