### ISSUE TITLE
Replaces with spaces the braces

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#19]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Replaces with spaces the braces in cases where braces in places cause stasis
| Search Keywords | replace, braces, stasis

```php
// Replaces with spaces the braces in cases where braces in places cause stasis 
$str = str_replace(array("\{","\}")," ",$str);
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/20

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/php/replaces-with-spaces-the-braces
