### ISSUE TITLE
Controller method that does a lot - eh not.

### ISSUE THREAD

**Issue by tobi812** [codequote/submit#23]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Function was found in an abstract controller class.
| Search Keywords | controller, response, abstract, senseless

```php

/**
 * @param array $data
 *
 * @return array
 */
protected function viewResponse(array $data = [])
{
    return $data;
}

```

**Comment by qwot** [comment]
Thanks for contributing @tobi812!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/24

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @tobi812, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/php/controller-method-that-does-a-lot-eh-not
