### ISSUE TITLE
Always returns true

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#25]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Always returns true
| Search Keywords | boolean, true, false, always

```php
/**
 * Always returns true.
 */
public boolean isAvailable() {
    return false;
}
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/26

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/php/always-returns-true
