### ISSUE TITLE
Constant Int TEN

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#27]
| Q               | A
| --------------- | ---
| Language        | c++
| Description     | It's always good to define some constants. To make sure everybody uses the same value!
| Search Keywords | constant, int, integer, value, ten, 10

```c++
const int TEN=10; // As if the value of 10 will fluctuate... 
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/28

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/c++/constant-int-ten
