### ISSUE TITLE
understand recursion

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#29]
| Q               | A
| --------------- | ---
| Language        | comment
| Description     | To know what recursion is, you have to know what recursion is
| Search Keywords | recursion, infinite loop

```php
# To understand recursion, see the bottom of this file 

...
...
...

# To understand recursion, see the top of this file
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/30

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/understand-recursion
