### ISSUE TITLE
Double check int and null, safety first!

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#3]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Double check ftw! Check if it's a integer AND if it's not null. Yip!
| Search Keywords | if, null, int

```LANGUAGE
if(is_int(intval($category)) && null !== $category) {
    $topicFacade=newPage_Helper_Facade();
    $topic=$topicFacade->getTopicById($category);
    $topicUrl=$topic->getUrl();
}
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/4

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: http://www.codequote.de/php/double-check-int-and-null-safety-first
