### ISSUE TITLE
No Comments for You

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#31]
| Q               | A
| --------------- | ---
| Language        | comment
| Description     | no comments for you, it was hard to write!
| Search Keywords | no comment, hard, read, write

```php
// no comments for you
// it was hard to write
// so it should be hard to read
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/32

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/comment/no-comments-for-you
