### ISSUE TITLE
Has to be there. Without an error appears.

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#33]
| Q               | A
| --------------- | ---
| Language        | perl
| Description     | Has to be there. Without an error appears.
| Search Keywords | no one knows

```perl
...

else # ??? Has to be there. Without an error appears. But no one knows why.
{
    next;
}
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/34

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/perl/has-to-be-there-without-an-error-appears
