### ISSUE TITLE
12 is my lucky number

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#35]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | This isn't the right way to deal with this, but today is my last day!
| Search Keywords | last day, coffee, hungry, 12, twelve, lucky, lucky number

```php
/*
 * This isn't the right way to deal with this, but today is my last day, Ron
 * just spilled coffee on my desk, and I'm hungry, so this will have to do...
 */

return 12; // 12 is my lucky number
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/36

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: https://codequote.wtf/php/12-is-my-lucky-number
