### ISSUE TITLE
Converts a time HH:MM:SS into seconds

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#5]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Converts a time HH:MM:SS in seconds
| Search Keywords | time, convert, transform, second, seconds, explode

```php
/**
 * Converts a time HH:MM:SS into seconds
 *
 * @param  string $time
 * @return integer
 */
function convertGermanTimeToSeconds($time) {

  list($hours, $minutes) = explode(':', $time);
  return ((int) $hours * 60 * 60 + (int) $minutes * 60);
}

```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/6

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: http://www.codequote.de/php/converts-a-time-hhmmss-into-seconds
