### ISSUE TITLE
Fresh Data By Asking Propel 2 Times

### ISSUE THREAD

**Issue by florianpreusner** [codequote/submit#7]
| Q               | A
| --------------- | ---
| Language        | php
| Description     | Yes, why not asking the database two times for a contact? Keeping it fresh!
| Search Keywords | propel, symfony, retrieve, duplicate, denglisch, denglish

```php
if(is_object(KontaktPeer::retrieveByPK($request->getParameter('contact_id')))) {
  $this->contact = KontaktPeer::retrieveByPK($request->getParameter('contact_id'));
} else {
  $this->redirect('@contact_index');
}
```

**Comment by qwot** [comment]
Thanks for contributing @florianpreusner!
I've created a Pull Request based on your issue: PR https://github.com/codequote/submit/pull/8

After reviewing your quote it will be merged and deployed. I will keep you informed!
\- qwot (Codequote Bot)

**Comment by qwot** [comment]
Hey @florianpreusner, I got some good news for you!
Your quote has been deployed on codequote.de :tada:

:arrow_forward: http://www.codequote.de/php/fresh-data-by-asking-propel-2-times
